version: "3.9"

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--providers.file.filename=/etc/traefik/dynamic.yml"
    ports:
      - "80:80"         # HTTP
      - "8080:8080"     # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik-dynamic.yml:/etc/traefik/dynamic.yml:rw
    networks:
      - traefik-net

  frontend:
    build: ./frontend
    environment:
      - PORT=80
      - SERVICE_ID=frontend
    expose:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`detfsmm.com`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
    networks:
      - traefik-net

  backend:
    build: ./backend
    environment:
      - PORT=9000
      - SERVICE_ID=backend
    expose:
      - "9000"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`detfsmm.com`) && PathPrefix(`/api`)"
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.services.backend.loadbalancer.server.port=9000"
    networks:
      - traefik-net

  backend1:
    build: ./backend
    environment:
      - PORT=9000
      - SERVICE_ID=backend1
    expose:
      - "9000"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`detfsmm.com`) && PathPrefix(`/api`)"
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.services.backend.loadbalancer.server.port=9000"
    networks:
      - traefik-net

  backend2:
    build: ./backend
    environment:
      - PORT=9000
      - SERVICE_ID=backend2
    expose:
      - "9000"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`detfsmm.com`) && PathPrefix(`/api`)"
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.services.backend.loadbalancer.server.port=9000"
    networks:
      - traefik-net

networks:
  traefik-net:
    driver: bridge here