version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - frontend
      - backend1
      - backend2
      - backend3
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - REACT_APP_API_BASE_URL=/api

  backend1:
    build: ./backend
    environment:
      - PORT=9000
      - SERVICE_ID=backend1
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health"]
      interval: 10s
      timeout: 3s
      retries: 3

  backend2:
    build: ./backend
    environment:
      - PORT=9000
      - SERVICE_ID=backend2
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health"]
      interval: 10s
      timeout: 3s
      retries: 3

  backend3:
    build: ./backend
    environment:
      - PORT=9000
      - SERVICE_ID=backend3
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health"]
      interval: 10s
      timeout: 3s
      retries: 3

networks:
  app-network:
    driver: bridge